### ISSUE TITLE
WB002: Deposit Account Service

### ISSUE THREAD

**Issue by Arielpetit** [ADORSYS-GIS/webank-OnlineBanking#31]
## Subtask of 
- ADORSYS-GIS/webank#56 

## Subtasks
- [ ] ADORSYS-GIS/webbank-BankAccount#12
- [ ] ADORSYS-GIS/webank-OnlineBanking#28
- [ ] ADORSYS-GIS/webank-BankAccount#48
